-- Habilitar la extensión uuid-ossp
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA public;

-- Establecer el esquema de búsqueda por defecto
SET search_path = public;

-- 1. Eliminar la tabla existente si ya existe y quieres recrearla desde cero
DROP TABLE IF EXISTS public.species CASCADE;

-- 2. Creación de la tabla de Especies (species)
CREATE TABLE public.species (
    id_specie uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    scientific_name text UNIQUE NOT NULL,
    common_name text NOT NULL,
    type text NOT NULL,
    habitat text NOT NULL,
    size text,
    ecological_role text,
    conservation_status text,
    description text,
    distribution text,
    family text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Crear índices para mejorar el rendimiento de búsqueda
CREATE INDEX idx_species_scientific_name ON public.species (scientific_name);
CREATE INDEX idx_species_common_name ON public.species (common_name);
CREATE INDEX idx_species_type ON public.species (type);
CREATE INDEX idx_species_habitat ON public.species (habitat);
CREATE INDEX idx_species_conservation_status ON public.species (conservation_status);



INSERT INTO public.species (id_specie, scientific_name, common_name, type, habitat, size, ecological_role, conservation_status, description, distribution, family) VALUES
(uuid_generate_v4(), 'Espeletia grandiflora', 'Frailejón común/de oso', 'Planta', 'Páramos andinos (principalmente zonas bajas y medias)', 'Hasta 5 metros de altura con rosetas foliares de 1-2 metros de diámetro.', 'Productor primario, regulador hídrico, hábitat para fauna, fijador de suelo.', 'Preocupación Menor (LC)', 'Especie emblemática de los páramos andinos, caracterizada por su tallo robusto y roseta de hojas vellosas que capturan el agua atmosférica.', 'Páramos de Colombia y Venezuela.', 'Asteraceae'),
(uuid_generate_v4(), 'Espeletia hartwegiana', 'Frailejón de Hartweg', 'Planta', 'Páramos andinos (principalmente zonas bajas y medias)', 'Hasta 3 metros de altura con una roseta de hojas grandes y pilosas.', 'Productor primario, regulador hídrico, hábitat para microfauna.', 'Preocupación Menor (LC)', 'Frailejón común en los Andes colombianos, de aspecto robusto y hojas recubiertas de tricomas que le dan una apariencia blanquecina.', 'Páramos de Colombia y Ecuador.', 'Asteraceae'),
(uuid_generate_v4(), 'Espeletia pycnophylla', 'Frailejón de hojas densas', 'Planta', 'Páramos andinos altos y superpáramos', 'Hasta 4 metros de altura con hojas muy densas y superpuestas en la roseta.', 'Productor primario, regulador hídrico, adaptado a condiciones extremas de altura.', 'Preocupación Menor (LC)', 'Especie de frailejón que se distingue por la compactación de sus hojas, lo que le permite resistir bajas temperaturas y vientos fuertes en alturas elevadas.', 'Páramos de Colombia y Ecuador.', 'Asteraceae'),
(uuid_generate_v4(), 'Espeletia argentea', 'Frailejón plateado', 'Planta', 'Páramos andinos (zonas medias y altas)', 'Hasta 2.5 metros de altura, con hojas cubiertas de densos pelos plateados.', 'Productor primario, captador de agua, hábitat para insectos.', 'Preocupación Menor (LC)', 'Nombrada por el color plateado de sus hojas, debido a una densa pubescencia que la protege del frío y la radiación solar intensa.', 'Páramos de Colombia.', 'Asteraceae'),
(uuid_generate_v4(), 'Espeletiopsis corymbosa', 'Frailejón falso', 'Planta', 'Páramos y subpáramos', 'Arbusto de hasta 3 metros de altura, con inflorescencias en corimbo.', 'Productor primario, proporciona alimento y refugio a la fauna.', 'Preocupación Menor (LC)', 'Género cercano a Espeletia, con especies que comparten características morfológicas similares a los frailejones, pero con diferencias en la estructura floral.', 'Páramos de Colombia y Venezuela.', 'Asteraceae'),
(uuid_generate_v4(), 'Coespeletia timotensis', '(Frailejón de Timotes)', 'Planta', 'Páramos de alta montaña', 'Hasta 3 metros de altura.', 'Productor primario, indicador de salud del ecosistema de páramo.', 'Casi Amenazada (NT)', 'Aunque más común en Venezuela, algunas poblaciones o híbridos pueden encontrarse en los páramos fronterizos de Colombia. Posee hojas grandes y pubescentes.', 'Páramos de Venezuela (posiblemente Colombia).', 'Asteraceae'),
(uuid_generate_v4(), 'Libanothamnus neriifolius', 'Tabacote morado', 'Planta', 'Páramos y subpáramos', 'Arbusto de hasta 3 metros de altura.', 'Productor primario, fuente de alimento para aves y mamíferos.', 'Preocupación Menor (LC)', 'Arbusto con hojas lanceoladas y flores vistosas que atraen polinizadores, común en el sotobosque de los páramos andinos.', 'Páramos de Colombia y Venezuela.', 'Asteraceae'),
(uuid_generate_v4(), 'Pentacalia ledifolia', 'Chilca de páramo', 'Planta', 'Páramos y bosques altoandinos', 'Arbusto o pequeño árbol de hasta 4 metros de altura.', 'Productor primario, provee cobertura y alimento.', 'Preocupación Menor (LC)', 'Arbusto leñoso con hojas coriáceas, común en los páramos, a menudo formando parte de la vegetación arbustiva de transición.', 'Andes de Colombia.', 'Asteraceae'),
(uuid_generate_v4(), 'Baccharis tricuneata', 'Romerito de páramo', 'Planta', 'Páramos y subpáramos', 'Arbusto bajo, de 0.5 a 1.5 metros de altura.', 'Productor primario, colonizador de suelos degradados, fuente de alimento.', 'Preocupación Menor (LC)', 'Arbusto aromático con hojas pequeñas y aglomeradas, que forma densos matorrales en el páramo, ofreciendo refugio a la fauna menor.', 'Andes de Colombia y Ecuador.', 'Asteraceae'),
(uuid_generate_v4(), 'Gynoxys fuliginosa', 'Árnica de páramo', 'Planta', 'Páramos y subpáramos', 'Hierba o arbusto de hasta 1.5 metros de altura, con flores amarillas.', 'Productor primario, fuente de alimento y con propiedades medicinales tradicionales.', 'Preocupación Menor (LC)', 'Planta vistosa con flores amarillas brillantes, utilizada tradicionalmente por sus propiedades antiinflamatorias y analgésicas.', 'Andes de Colombia, Ecuador y Perú.', 'Asteraceae'),
(uuid_generate_v4(), 'Senecio niveoaureus', 'Senecio dorado', 'Planta', 'Páramos andinos', 'Hierba perenne de hasta 60 cm de altura, con flores amarillas.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Hierba con hojas aterciopeladas y flores de color amarillo intenso, común en zonas abiertas del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Asteraceae'),
(uuid_generate_v4(), 'Werneria nubigena', 'Werneria de las nubes', 'Planta', 'Páramos y superpáramos', 'Hierba rastrera o en cojín, de pocos centímetros de altura.', 'Productor primario, formador de microhábitats, fijador de suelo.', 'Preocupación Menor (LC)', 'Pequeña planta que crece formando cojines densos, adaptada a las condiciones extremas de los páramos altos, donde ayuda a retener la humedad.', 'Andes de Colombia, Ecuador y Perú.', 'Asteraceae'),
(uuid_generate_v4(), 'Loricaria complanata', 'Loricaria', 'Planta', 'Páramos y bosques altoandinos', 'Arbusto o árbol pequeño de hasta 5 metros de altura.', 'Productor primario, soporte estructural, fuente de alimento y resina.', 'Preocupación Menor (LC)', 'Arbusto o árbol con hojas que a menudo están cubiertas de una resina pegajosa, común en áreas húmedas del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Asteraceae'),
(uuid_generate_v4(), 'Diplostephium phylicoides', 'Falso romero', 'Planta', 'Páramos y subpáramos', 'Arbusto de hasta 2 metros de altura.', 'Productor primario, ofrece refugio a pequeños animales.', 'Preocupación Menor (LC)', 'Arbusto con hojas lineales y flores similares a margaritas, que se asemeja al romero y es muy común en los paisajes de páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Asteraceae'),
(uuid_generate_v4(), 'Ageratina tinifolia', 'Salvia amarga de páramo', 'Planta', 'Páramos y bosques altoandinos', 'Arbusto de hasta 2 metros de altura.', 'Productor primario, fuente de alimento para insectos y con posibles usos medicinales.', 'Preocupación Menor (LC)', 'Arbusto con hojas aromáticas y flores blancas, a menudo confundido con salvia debido a su forma, pero pertenece a las Asteraceae.', 'Andes de Colombia y Ecuador.', 'Asteraceae'),
(uuid_generate_v4(), 'Chaptalia cordata', 'Valeriana de páramo (no es Valeriana real)', 'Planta', 'Páramos y zonas húmedas', 'Hierba perenne de hasta 40 cm de altura, con hojas basales en roseta.', 'Productor primario, fuente de alimento para insectos.', 'Preocupación Menor (LC)', 'Planta herbácea con hojas en forma de corazón en la base, que produce una vara floral con una sola flor o un racimo de flores en la punta.', 'Andes de Colombia y Ecuador.', 'Asteraceae'),

-- Gramíneas y Ciperáceas (Poaceae, Cyperaceae)
(uuid_generate_v4(), 'Calamagrostis effusa', 'Pajonal de páramo', 'Planta', 'Páramos (dominante en zonas abiertas)', 'Hasta 1.5 metros de altura.', 'Productor primario, formador de ecosistema, alimento para herbívoros, regulador hídrico.', 'Preocupación Menor (LC)', 'Gramínea dominante en los pajonales de páramo, formando vastas extensiones que son cruciales para la retención de agua y la prevención de la erosión.', 'Andes de Colombia, Ecuador y Perú.', 'Poaceae'),
(uuid_generate_v4(), 'Chusquea tessellata', 'Chusque o bambú de páramo', 'Planta', 'Páramos (especialmente en áreas protegidas)', 'Hasta 5 metros de altura, formando densos matorrales.', 'Productor primario, formador de hábitat, alimento para fauna (especialmente el oso de anteojos).', 'Preocupación Menor (LC)', 'Bambú de páramo que forma densos cañaverales, proporcionando refugio y alimento a numerosas especies de fauna andina.', 'Andes de Colombia, Ecuador y Perú.', 'Poaceae'),
(uuid_generate_v4(), 'Festuca dolichophylla', 'Festuca de páramo', 'Planta', 'Páramos y superpáramos', 'Hasta 60 cm de altura, formando macollas.', 'Productor primario, componente de la vegetación del pajonal.', 'Preocupación Menor (LC)', 'Otra gramínea importante que crece en macollas, adaptada a las condiciones de frío y alta radiación, contribuyendo a la estabilidad del suelo.', 'Andes de Colombia, Ecuador y Perú.', 'Poaceae'),
(uuid_generate_v4(), 'Agrostis perennans', 'Pasto de páramo', 'Planta', 'Páramos y subpáramos', 'Hasta 80 cm de altura.', 'Productor primario, parte de la dieta de herbívoros.', 'Preocupación Menor (LC)', 'Pasto fino y común en los páramos, que contribuye a la formación del suelo y la cobertura vegetal.', 'Andes de Colombia.', 'Poaceae'),
(uuid_generate_v4(), 'Carex bonplandii', 'Cortadera de Bonpland', 'Planta', 'Zonas húmedas y pantanosas del páramo', 'Hasta 1 metro de altura, formando densos grupos.', 'Productor primario, estabilizador de riberas, formador de microhábitats.', 'Preocupación Menor (LC)', 'Ciperácea común en los humedales de páramo, con hojas largas y cortantes, importante para la estructura de la vegetación en áreas encharcadas.', 'Andes de Colombia, Ecuador y Perú.', 'Cyperaceae'),
(uuid_generate_v4(), 'Rhynchospora paramora', 'Rhynchospora de páramo', 'Planta', 'Zonas húmedas y pantanosas del páramo', 'Hasta 50 cm de altura.', 'Productor primario, parte de la vegetación de humedales.', 'Preocupación Menor (LC)', 'Otra ciperácea típica de las áreas pantanosas del páramo, contribuyendo a la biodiversidad de los microhábitats acuáticos.', 'Andes de Colombia.', 'Cyperaceae'),

-- Rosáceas (Rosaceae)
(uuid_generate_v4(), 'Polylepis quadrijuga', 'Colorado, Siete Cueros de páramo', 'Planta', 'Páramos (formando bosques de Polylepis)', 'Hasta 15 metros de altura.', 'Productor primario, formador de ecosistema (bosques de mayor altitud), refugio y alimento para fauna endémica.', 'En Peligro (EN)', 'Árbol de mayor altitud en los Andes, conocido por su corteza que se desprende en capas. Sus bosques son ecosistemas únicos y críticos para muchas especies andinas.', 'Andes de Colombia, Ecuador y Perú.', 'Rosaceae'),
(uuid_generate_v4(), 'Acaena elongata', 'Cadillo de páramo', 'Planta', 'Páramos y subpáramos', 'Hierba rastrera o ascendente, de hasta 50 cm de altura.', 'Productor primario, colonizador de suelos, sus frutos con espinas ayudan a la dispersión de semillas.', 'Preocupación Menor (LC)', 'Planta con frutos espinosos que se adhieren a la ropa y al pelaje de los animales, facilitando su dispersión a largas distancias.', 'Andes de Colombia, Ecuador y Perú.', 'Rosaceae'),
(uuid_generate_v4(), 'Lachemilla orbiculata', 'Guardarocío', 'Planta', 'Páramos (zonas húmedas)', 'Hierba rastrera de pocos centímetros de altura, con hojas redondas.', 'Productor primario, formador de microhábitat, retención de humedad.', 'Preocupación Menor (LC)', 'Pequeña hierba que forma tapetes densos sobre el suelo, a menudo con gotas de rocío atrapadas en sus hojas, de ahí su nombre común.', 'Andes de Colombia, Ecuador y Perú.', 'Rosaceae'),

-- Ericáceas (Ericaceae) - Arándanos y parientes
(uuid_generate_v4(), 'Vaccinium floribundum', 'Mortiño, agraz de páramo', 'Planta', 'Páramos y bosques altoandinos', 'Arbusto de 0.5 a 3 metros de altura.', 'Productor primario, alimento para aves y mamíferos (frutos), polinizador.', 'Preocupación Menor (LC)', 'Arbusto que produce bayas comestibles de color azul oscuro, muy apreciadas y consumidas por la fauna y las comunidades locales.', 'Andes de Colombia, Ecuador y Perú.', 'Ericaceae'),
(uuid_generate_v4(), 'Pernettya prostrata', 'Arrayancillo', 'Planta', 'Páramos y subpáramos', 'Arbusto rastrero o bajo, de hasta 50 cm de altura.', 'Productor primario, alimento para aves (frutos).', 'Preocupación Menor (LC)', 'Arbusto pequeño con hojas perennes y bayas de colores brillantes (rojas, blancas o rosadas), comunes en el sotobosque del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Ericaceae'),
(uuid_generate_v4(), 'Gaultheria anastomosans', 'Gaultheria', 'Planta', 'Páramos y bosques altoandinos', 'Arbusto de hasta 1.5 metros de altura.', 'Productor primario, alimento para fauna, con follaje aromático.', 'Preocupación Menor (LC)', 'Arbusto con hojas aromáticas y flores en forma de campana, seguido de frutos carnosos. Algunas especies tienen usos medicinales.', 'Andes de Colombia y Ecuador.', 'Ericaceae'),
(uuid_generate_v4(), 'Macleania rupestris', 'Uva camarona', 'Planta', 'Páramos y bordes de bosque andino', 'Arbusto epífito o terrestre, con tallos colgantes o rastreros.', 'Productor primario, alimento para aves (frutos).', 'Preocupación Menor (LC)', 'Planta con flores tubulares y bayas comestibles de color rojo o anaranjado, a menudo creciendo sobre rocas o como epífita en árboles del bosque de niebla.', 'Andes de Colombia y Ecuador.', 'Ericaceae'),
(uuid_generate_v4(), 'Disterigma empetrifolium', 'Disterigma', 'Planta', 'Páramos y superpáramos', 'Arbusto bajo, rastrero o en cojín, de pocos centímetros de altura.', 'Productor primario, colonizador de rocas y suelos pobres.', 'Preocupación Menor (LC)', 'Pequeño arbusto que forma tapetes densos, adaptado a las condiciones extremas de altitud y exposición al viento.', 'Andes de Colombia.', 'Ericaceae'),

-- Puyas (Bromeliaceae)
(uuid_generate_v4(), 'Puya goudotiana', 'Puya de Goudot', 'Planta', 'Páramos rocosos y laderas', 'Roseta de hasta 1.5 metros de diámetro, inflorescencia hasta 3 metros de altura.', 'Productor primario, polinizador (atrae colibríes y aves), hábitat para microfauna.', 'Preocupación Menor (LC)', 'Bromelia terrestre con una gran roseta de hojas espinosas y una impresionante inflorescencia columnar con flores vistosas, que atrae a diversos polinizadores.', 'Páramos de Colombia.', 'Bromeliaceae'),
(uuid_generate_v4(), 'Puya nivalis', 'Puya de las nieves', 'Planta', 'Páramos altos y superpáramos', 'Roseta de hasta 1 metro de diámetro, inflorescencia de 1-2 metros.', 'Productor primario, adaptada a condiciones de frío extremo, hábitat para pequeños insectos.', 'Preocupación Menor (LC)', 'Especie de Puya que se encuentra en las zonas más frías y nevadas de los páramos, con un aspecto robusto y hojas recubiertas para protegerse.', 'Páramos de Colombia y Ecuador.', 'Bromeliaceae'),
(uuid_generate_v4(), 'Puya trianae', 'Puya de Triana', 'Planta', 'Páramos y laderas rocosas', 'Roseta de hasta 1.2 metros de diámetro, inflorescencia hasta 2.5 metros de altura.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Bromelia de gran tamaño, similar a otras puyas, con hojas espinosas y una espiga floral llamativa que emerge desde el centro de la roseta.', 'Páramos de Colombia.', 'Bromeliaceae'),

-- Otras familias de plantas
(uuid_generate_v4(), 'Hypericum laricifolium', 'Chite, corazoncillo', 'Planta', 'Páramos y subpáramos', 'Arbusto de hasta 3 metros de altura.', 'Productor primario, alimento y refugio para fauna, con propiedades medicinales.', 'Preocupación Menor (LC)', 'Arbusto con hojas pequeñas y flores amarillas brillantes, muy común en los páramos, a menudo formando matorrales densos.', 'Andes de Colombia, Ecuador y Perú.', 'Hypericaceae'),
(uuid_generate_v4(), 'Gentiana sedifolia', 'Genciana de páramo', 'Planta', 'Páramos (zonas húmedas y turberas)', 'Hierba pequeña de hasta 15 cm de altura, con flores azules.', 'Productor primario, polinizador, indicador de calidad del suelo.', 'Preocupación Menor (LC)', 'Pequeña hierba con flores azules o púrpuras en forma de trompeta, típica de los suelos húmedos y musgosos del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Gentianaceae'),
(uuid_generate_v4(), 'Gentianella corymbosa', 'Gencianela', 'Planta', 'Páramos y subpáramos', 'Hierba de hasta 50 cm de altura, con flores en corimbo.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Planta herbácea con flores en forma de embudo, a menudo de colores vibrantes como el azul o el púrpura, comunes en los pastizales del páramo.', 'Andes de Colombia y Ecuador.', 'Gentianaceae'),
(uuid_generate_v4(), 'Halenia weddelliana', 'Halenia', 'Planta', 'Páramos y zonas húmedas', 'Hierba de hasta 40 cm de altura, con flores amarillo-verdosas.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Planta herbácea con flores tubulares de color verde-amarillento, a menudo con manchas. Crece en zonas pantanosas y húmedas del páramo.', 'Andes de Colombia y Ecuador.', 'Gentianaceae'),
(uuid_generate_v4(), 'Valeriana plantaginea', 'Valeriana de páramo', 'Planta', 'Páramos y subpáramos', 'Hierba de hasta 60 cm de altura, con flores blancas o rosadas.', 'Productor primario, polinizador, con propiedades medicinales (sedante).', 'Preocupación Menor (LC)', 'Planta herbácea con hojas basales y flores pequeñas, conocida por sus propiedades calmantes, usada en medicina tradicional.', 'Andes de Colombia y Ecuador.', 'Caprifoliaceae'),
(uuid_generate_v4(), 'Lupinus alopecuroides', 'Lupino de páramo, chocho de páramo', 'Planta', 'Páramos y laderas', 'Hierba o arbusto de hasta 1.5 metros de altura, con inflorescencias en espiga.', 'Productor primario, fijador de nitrógeno en el suelo, alimento para herbívoros.', 'Preocupación Menor (LC)', 'Planta con grandes y vistosas espigas florales de color azul-violeta, que enriquece el suelo al fijar nitrógeno. Sus semillas son consumidas en algunas culturas andinas.', 'Andes de Colombia, Ecuador y Perú.', 'Fabaceae'),
(uuid_generate_v4(), 'Draba litamo', 'Draba del Litamo', 'Planta', 'Páramos y superpáramos (endemismo)', 'Hierba perenne, pequeña, de pocos centímetros de altura.', 'Productor primario, colonizador de suelos rocosos.', 'Datos Insuficientes (DD)', 'Pequeña hierba endémica, adaptada a las condiciones de alta montaña, a menudo creciendo en grietas de rocas o suelos pedregosos.', 'Páramos de Colombia.', 'Brassicaceae'),
(uuid_generate_v4(), 'Plantago rigida', 'Llantén de páramo', 'Planta', 'Páramos (formador de cojines)', 'Hierba pequeña, forma densos cojines de hasta 30 cm de diámetro.', 'Productor primario, formador de ecosistema, retención de agua, estabilizador de suelo.', 'Preocupación Menor (LC)', 'Planta que crece formando cojines compactos sobre el suelo, crucial para la retención de agua y la creación de microhábitats en los páramos anegados.', 'Andes de Colombia, Ecuador y Perú.', 'Plantaginaceae'),
(uuid_generate_v4(), 'Azorella crenata', 'Azorella', 'Planta', 'Páramos (formador de cojines)', 'Hierba pequeña, forma densos cojines de hasta varios metros de diámetro.', 'Productor primario, formador de ecosistema, retención de agua, protección contra la erosión.', 'Preocupación Menor (LC)', 'Planta que forma grandes y duros cojines sobre el suelo rocoso del páramo, actuando como una "esponja" natural que absorbe y libera agua lentamente.', 'Andes de Colombia, Ecuador y Perú.', 'Apiaceae'),
(uuid_generate_v4(), 'Arcytophyllum muticum', 'Coralito de páramo', 'Planta', 'Páramos y subpáramos', 'Arbusto pequeño de hasta 1 metro de altura, con flores tubulares rojas o anaranjadas.', 'Productor primario, polinizador (atrae colibríes).', 'Preocupación Menor (LC)', 'Arbusto con flores tubulares de colores vistosos que atraen a los colibríes, común en los matorrales del páramo.', 'Andes de Colombia y Ecuador.', 'Rubiaceae'),
(uuid_generate_v4(), 'Castilleja fissifolia', 'Pincelito de páramo', 'Planta', 'Páramos y subpáramos', 'Hierba hemiparásita de hasta 40 cm de altura, con brácteas coloreadas.', 'Hemiparásito (se alimenta de raíces de otras plantas), atrae polinizadores.', 'Preocupación Menor (LC)', 'Planta hemiparásita con brácteas terminales de colores brillantes (rojo, naranja), que le dan el aspecto de un "pincel", atrayendo a polinizadores.', 'Andes de Colombia, Ecuador y Perú.', 'Orobanchaceae'),
(uuid_generate_v4(), 'Calceolaria herbeohybrida', 'Zapatito de páramo', 'Planta', 'Páramos y subpáramos (zonas húmedas)', 'Hierba de hasta 50 cm de altura, con flores en forma de zapatito.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Planta con flores muy características en forma de pequeña bolsa o "zapatito", a menudo amarillas con manchas, comunes en zonas húmedas del páramo.', 'Andes de Colombia.', 'Calceolariaceae'),
(uuid_generate_v4(), 'Ourisia chamaedrifolia', 'Ourisia', 'Planta', 'Páramos y zonas húmedas rocosas', 'Hierba rastrera o en roseta, de pocos centímetros de altura, con flores blancas o rosadas.', 'Productor primario, formador de microhábitat.', 'Preocupación Menor (LC)', 'Pequeña hierba que crece en ambientes húmedos y rocosos, con flores delicadas que emergen de las rosetas basales.', 'Andes de Colombia y Ecuador.', 'Plantaginaceae'),
(uuid_generate_v4(), 'Lysipomia sphagnophila', 'Lisipomia de musgo', 'Planta', 'Turberas y pantanos de páramo', 'Hierba pequeña, crece asociada a musgos, de pocos centímetros de altura.', 'Productor primario, componente de la flora de turberas.', 'Datos Insuficientes (DD)', 'Pequeña planta herbácea que se encuentra específicamente en los pantanos y turberas de páramo, a menudo creciendo directamente sobre capas de musgo Sphagnum.', 'Andes de Colombia.', 'Campanulaceae'),
(uuid_generate_v4(), 'Gunnera magellanica', 'Ruibarbo de páramo (pequeño)', 'Planta', 'Zonas muy húmedas y pantanosas del páramo', 'Hierba rastrera de pocos centímetros de altura, con hojas grandes para su tamaño.', 'Productor primario, fijador de nitrógeno (asociación con cianobacterias), componente de turberas.', 'Preocupación Menor (LC)', 'Pequeña planta que se asemeja al ruibarbo, con hojas grandes y carnosas. Forma extensas coberturas en zonas muy húmedas, fijando nitrógeno atmosférico.', 'Andes y Patagonia.', 'Gunneraceae'),
(uuid_generate_v4(), 'Ranunculus peruvianus', 'Botón de oro de páramo', 'Planta', 'Zonas húmedas y orillas de cuerpos de agua en páramo', 'Hierba perenne de hasta 40 cm de altura, con flores amarillas.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Flor herbácea con pétalos brillantes de color amarillo intenso, común en las orillas de lagunas y arroyos en el páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Ranunculaceae'),
(uuid_generate_v4(), 'Geranium sibbaldioides', 'Geranio de páramo', 'Planta', 'Páramos y subpáramos', 'Hierba de hasta 30 cm de altura, con flores rosadas o púrpuras.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Pequeño geranio silvestre adaptado a las condiciones de los páramos, con flores delicadas y hojas lobuladas.', 'Andes de Colombia, Ecuador y Perú.', 'Geraniaceae'),
(uuid_generate_v4(), 'Oxalis medicaginea', 'Vinagrillo de páramo', 'Planta', 'Páramos y zonas abiertas', 'Hierba rastrera o erecta, de pocos centímetros de altura, con hojas trifoliadas.', 'Productor primario, fuente de alimento (hojas comestibles ácidas).', 'Preocupación Menor (LC)', 'Planta pequeña con hojas en forma de trébol, de sabor ácido, común en los pastizales y zonas abiertas del páramo.', 'Andes de Colombia.', 'Oxalidaceae'),
(uuid_generate_v4(), 'Jamesonia bogotensis', 'Helecho de cuero', 'Planta', 'Páramos rocosos y taludes', 'Helecho terrestre de hasta 50 cm de altura, con frondas coriáceas.', 'Productor primario, formador de microhábitat.', 'Preocupación Menor (LC)', 'Helecho robusto con frondas rígidas y coriáceas, adaptado a las condiciones de viento y sequedad de los páramos rocosos.', 'Andes de Colombia.', 'Pteridaceae'),
(uuid_generate_v4(), 'Huperzia crassa', 'Licopodio de páramo', 'Planta', 'Páramos (zonas húmedas y musgosas)', 'Licopodio epífito o terrestre, con tallos ramificados y densamente cubiertos de hojas.', 'Productor primario, colonizador, formador de microhábitat.', 'Preocupación Menor (LC)', 'Planta parecida a un musgo gigante o pequeño pino, común en suelos húmedos y turberas, a menudo formando densas alfombras.', 'Andes de Sudamérica.', 'Lycopodiaceae'),
(uuid_generate_v4(), 'Isoetes palmeri', 'Isoetes', 'Planta', 'Lagunas y humedales de páramo (acuática/semiacuática)', 'Planta acuática sumergida, con hojas quilladas de hasta 20 cm.', 'Productor primario, purificador de agua, alimento para peces.', 'Preocupación Menor (LC)', 'Planta acuática que crece en el fondo de lagunas y cuerpos de agua de páramo, con hojas que se asemejan a pequeños quillones.', 'Andes de Colombia y Ecuador.', 'Isoetaceae'),
(uuid_generate_v4(), 'Sphagnum magellanicum', 'Musgo de turbera', 'Planta', 'Turberas y pantanos de páramo (dominante)', 'Musgo que forma densas capas o cojines de hasta 30 cm de profundidad.', 'Productor primario, formador de turba, regulador hídrico, hábitat para invertebrados.', 'Preocupación Menor (LC)', 'Musgo fundamental en la formación de turberas, capaz de retener grandes volúmenes de agua, crucial para la regulación hídrica del páramo.', 'Distribución global en climas fríos y templados.', 'Sphagnaceae'),

-- Orquídeas de altura
(uuid_generate_v4(), 'Epidendrum aggregatum', 'Orquídea de páramo', 'Planta', 'Páramos y bosques altoandinos (epífita o terrestre)', 'Variable, pseudobulbos de 2-5 cm, flores pequeñas en racimos.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Orquídea epífita o terrestre, común en los páramos, con flores pequeñas y coloridas que se agrupan en racimos densos.', 'Andes de Colombia y Ecuador.', 'Orchidaceae'),
(uuid_generate_v4(), 'Masdevallia coccinea', 'Masdevallia roja', 'Planta', 'Bosques de niebla y zonas húmedas de páramo', 'Plantas pequeñas (10-30 cm), flores de 5-10 cm de diámetro.', 'Productor primario, polinizador.', 'Casi Amenazada (NT)', 'Orquídea de flores grandes y llamativas, predominantemente rojas, común en zonas húmedas y musgosas del subpáramo y páramo.', 'Andes de Colombia y Ecuador.', 'Orchidaceae'),
(uuid_generate_v4(), 'Elleanthus aurantiacus', 'Elleanthus naranja', 'Planta', 'Páramos y subpáramos', 'Plantas de 30-80 cm de altura, con racimos de flores anaranjadas.', 'Productor primario, polinizador.', 'Preocupación Menor (LC)', 'Orquídea terrestre o epífita, con tallos erectos y flores de color naranja brillante agrupadas en densos racimos terminales.', 'Andes de Colombia, Ecuador y Perú.', 'Orchidaceae'),

-- MAMÍFEROS
(uuid_generate_v4(), 'Tremarctos ornatus', 'Oso de anteojos, oso andino', 'Mamífero', 'Bosques andinos, páramos, bosques secos. Rango altitudinal amplio.', 'Altura a la cruz de 70-90 cm; peso de 60-200 kg.', 'Dispersor de semillas, polinizador, ingeniero de ecosistemas (al crear caminos y "camas"), depredador ocasional.', 'Vulnerable (VU)', 'Único oso de Sudamérica, omnívoro con una dieta predominantemente vegetariana. Crucial para la salud de los ecosistemas andinos, especialmente los bosques de niebla y páramos.', 'Andes desde Venezuela hasta Bolivia.', 'Ursidae'),
(uuid_generate_v4(), 'Tapirus pinchaque', 'Danta de montaña, tapir andino', 'Mamífero', 'Páramos, bosques de niebla y subpáramos.', 'Altura a la cruz de 80-100 cm; peso de 150-250 kg.', 'Gran dispersor de semillas, herbívoro principal que modela la vegetación.', 'En Peligro (EN)', 'El más pequeño de los tapires, adaptado a climas fríos. Solitario y nocturno, juega un rol vital en la dispersión de semillas de grandes frutos en su hábitat.', 'Andes de Colombia, Ecuador y Perú.', 'Tapiridae'),
(uuid_generate_v4(), 'Puma concolor', 'Puma', 'Mamífero', 'Amplia variedad de hábitats, incluyendo páramos, bosques andinos y subpáramos.', 'Longitud de 1.5-2.7 metros (incluyendo cola); peso de 30-100 kg.', 'Depredador tope, regulador de poblaciones de herbívoros.', 'Preocupación Menor (LC)', 'Felino de gran tamaño, solitario y territorial, con la distribución más amplia de cualquier mamífero terrestre en América. Es un depredador clave en los ecosistemas andinos.', 'Desde Canadá hasta el sur de la Patagonia.', 'Felidae'),
(uuid_generate_v4(), 'Odocoileus virginianus goudotii', 'Venado de cola blanca de páramo', 'Mamífero', 'Páramos y subpáramos andinos.', 'Altura a la cruz de 70-90 cm; peso de 40-70 kg.', 'Herbívoro, dispersor de semillas de plantas pequeñas.', 'Preocupación Menor (LC) - Subespecie no evaluada independientemente por UICN, pero las poblaciones de páramo pueden estar amenazadas localmente.', 'Subespecie de venado de cola blanca adaptada a las alturas andinas, con pelaje más denso y oscuro. Es un herbívoro importante en el páramo.', 'Páramos de Colombia y Venezuela.', 'Cervidae'),
(uuid_generate_v4(), 'Mazama rufina', 'Venado soche o colorado pequeño', 'Mamífero', 'Bosques de niebla y subpáramos, bordes de páramo.', 'Altura a la cruz de 40-50 cm; peso de 10-15 kg.', 'Herbívoro, dispersor de semillas.', 'Vulnerable (VU)', 'Pequeño venado de color rojizo, discreto y solitario, que habita en el sotobosque denso de los bosques montanos y se aventura en los bordes del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Cervidae'),
(uuid_generate_v4(), 'Pudu mephistophiles', 'Pudú del norte, venado conejo', 'Mamífero', 'Bosques de niebla, subpáramos y páramos.', 'Altura a la cruz de 30-35 cm; peso de 5-10 kg.', 'Herbívoro, dispersor de semillas de frutos pequeños.', 'Vulnerable (VU)', 'El cérvido más pequeño del mundo, con una apariencia similar a un conejo. Habita en la vegetación densa de páramos y bosques andinos, donde se alimenta de hojas y frutos.', 'Andes de Colombia, Ecuador y Perú.', 'Cervidae'),
(uuid_generate_v4(), 'Lycalopex culpaeus', 'Zorro culpeo andino', 'Mamífero', 'Páramos, valles interandinos y zonas abiertas.', 'Longitud de 60-120 cm (incluyendo cola); peso de 5-10 kg.', 'Depredador, carroñero, dispersor de semillas.', 'Preocupación Menor (LC)', 'El cánido silvestre más grande de Sudamérica, con un pelaje rojizo y cola espesa. Es un depredador oportunista que se alimenta de roedores, aves, conejos y carroña.', 'Andes de Sudamérica.', 'Canidae'),
(uuid_generate_v4(), 'Mustela frenata', 'Comadreja de cola larga', 'Mamífero', 'Amplia variedad de hábitats, incluyendo páramos, bosques y áreas agrícolas.', 'Longitud de 30-50 cm (incluyendo cola); peso de 100-400 g.', 'Depredador de pequeños mamíferos y aves.', 'Preocupación Menor (LC)', 'Pequeño mustélido de cuerpo alargado y ágil, con pelaje pardo y vientre amarillo. Un cazador eficiente de roedores y aves pequeñas en el páramo.', 'Desde Canadá hasta los Andes.', 'Mustelidae'),
(uuid_generate_v4(), 'Conepatus semistriatus', 'Zorrillo o mapurite de páramo', 'Mamífero', 'Bosques de niebla, subpáramos y páramos.', 'Longitud de 40-70 cm (incluyendo cola); peso de 1-3 kg.', 'Insectívoro, dispersor de semillas (frutos de cactus y otras plantas).', 'Preocupación Menor (LC)', 'Mamífero de hábitos nocturnos, conocido por su capacidad de rociar un líquido de olor fétido para defenderse. Se alimenta principalmente de insectos y pequeños invertebrados.', 'América Central y Sudamérica (incluyendo Andes).', 'Mephitidae'),
(uuid_generate_v4(), 'Sylvilagus andinus', 'Conejo de páramo', 'Mamífero', 'Páramos, subpáramos y zonas boscosas adyacentes.', 'Longitud de 30-45 cm; peso de 1-2 kg.', 'Herbívoro, base de la cadena alimenticia para depredadores.', 'Preocupación Menor (LC) - Especie recientemente reconocida, antes subespecie de S. brasiliensis.', 'Conejo silvestre endémico de los Andes, adaptado a las condiciones de altura. Se alimenta de pastos y vegetación del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Leporidae'),
(uuid_generate_v4(), 'Cuniculus taczanowskii', 'Tinajo o paca de montaña', 'Mamífero', 'Bosques de niebla, subpáramos y bordes de páramo (cerca de cuerpos de agua).', 'Longitud de 60-80 cm; peso de 7-12 kg.', 'Herbívoro (frugívoro/folívoro), dispersor de semillas.', 'Vulnerable (VU)', 'Roedor grande y robusto, con pelaje pardo y manchas blancas, que habita en zonas húmedas de bosques montanos. Es nocturno y solitario.', 'Andes de Colombia, Ecuador, Perú y Bolivia.', 'Cuniculidae'),
(uuid_generate_v4(), 'Dinomys branickii', 'Pacarana o Guagua de cola ancha', 'Mamífero', 'Bosques húmedos montanos, bordes de páramo.', 'Longitud de 70-80 cm; peso de 10-15 kg.', 'Herbívoro (frugívoro/folívoro), dispersor de semillas.', 'Casi Amenazada (NT)', 'Gran roedor de aspecto robusto, con cola corta y ancha. Habita en los bosques montanos, pero puede aventurarse en los bordes del páramo. Es nocturno y se alimenta de frutos y hojas.', 'Andes de Colombia, Ecuador, Perú y Bolivia.', 'Dinomyidae'),
(uuid_generate_v4(), 'Thomasomys niveipes', 'Ratón de páramo de patas blancas', 'Mamífero', 'Páramos y bosques altoandinos.', 'Longitud de cuerpo 10-15 cm; cola 12-18 cm; peso de 50-100 g.', 'Granívoro, insectívoro, dispersor de esporas de hongos, presa para depredadores.', 'Preocupación Menor (LC)', 'Roedor múrido adaptado a las alturas andinas, con patas blancas. Es una presa importante para aves rapaces y pequeños carnívoros.', 'Andes de Colombia y Ecuador.', 'Cricetidae'),
(uuid_generate_v4(), 'Chibchanomys orcesi', 'Ratón de agua de Orces', 'Mamífero', 'Arroyos y quebradas de páramo y bosque andino.', 'Longitud de cuerpo 10-12 cm; cola 10-14 cm; peso de 40-60 g.', 'Depredador de invertebrados acuáticos, bioindicador.', 'Datos Insuficientes (DD)', 'Ratón semiacuático especializado en la vida en arroyos de alta montaña, con patas palmeadas. Su presencia indica buena calidad de agua.', 'Andes de Colombia y Ecuador.', 'Cricetidae'),
(uuid_generate_v4(), 'Cryptotis colombiana', 'Musaraña colombiana de páramo', 'Mamífero', 'Páramos y subpáramos.', 'Longitud de cuerpo 6-8 cm; peso de 5-10 g.', 'Insectívoro (come pequeños invertebrados), controlador de poblaciones de insectos.', 'Vulnerable (VU)', 'Pequeña musaraña endémica de los páramos colombianos, con hocico alargado y ojos pequeños. Se alimenta de invertebrados en el suelo y la hojarasca.', 'Páramos de Colombia.', 'Soricidae'),
(uuid_generate_v4(), 'Coendou rufescens', 'Puercoespín de cola corta o erizo rojo', 'Mamífero', 'Bosques andinos, subpáramos y bordes de páramo.', 'Longitud de 40-60 cm; peso de 2-4 kg.', 'Herbívoro (folívoro, frugívoro), dispersor de semillas.', 'Preocupación Menor (LC)', 'Puercoespín arborícola con espinas cortas y rojizas, y una cola prensil. Nocturno, se alimenta de hojas, brotes y frutos.', 'Andes de Colombia, Ecuador y Perú.', 'Erethizontidae'),

-- AVES
(uuid_generate_v4(), 'Vultur gryphus', 'Cóndor de los Andes', 'Ave', 'Zonas montañosas, páramos y altas cumbres andinas, planeando sobre pastizales y acantilados.', 'Envergadura alar de hasta 3.3 metros; peso de 8-15 kg.', 'Carroñero, limpiador del ecosistema, indicador de salud ambiental.', 'Vulnerable (VU) globalmente; En Peligro Crítico (CR) en Colombia.', 'Una de las aves voladoras más grandes del mundo, símbolo de los Andes. Esencial para la remoción de carroña, evitando la propagación de enfermedades.', 'Cordillera de los Andes desde Venezuela hasta Tierra del Fuego.', 'Cathartidae'),
(uuid_generate_v4(), 'Geranoaetus melanoleucus', 'Águila mora', 'Ave', 'Páramos, zonas montañosas y valles andinos.', 'Envergadura alar de 1.8-2 metros; peso de 2-3 kg.', 'Depredador tope, controlador de poblaciones de roedores y serpientes.', 'Preocupación Menor (LC)', 'Gran ave rapaz con plumaje blanco y negro, y cola corta. Caza desde el aire y es un depredador eficiente de pequeños mamíferos y aves.', 'Andes de Sudamérica.', 'Accipitridae'),
(uuid_generate_v4(), 'Phalcoboenus carunculatus', 'Caracara paramuno', 'Ave', 'Páramos, pastizales de alta montaña.', 'Longitud de 50-60 cm; envergadura de 1.2-1.3 metros; peso de 1-1.5 kg.', 'Carroñero, depredador oportunista de insectos, pequeños mamíferos, huevos y carroña.', 'Preocupación Menor (LC)', 'Ave rapaz robusta y terrestre, con plumaje oscuro y cara rojiza con carúnculas. Se alimenta en el suelo y es un carroñero común en el páramo.', 'Andes de Colombia y Ecuador.', 'Falconidae'),
(uuid_generate_v4(), 'Falco sparverius', 'Cernícalo americano', 'Ave', 'Amplia variedad de hábitats, incluyendo páramos, zonas abiertas, agrícolas y urbanas.', 'Longitud de 20-30 cm; envergadura de 50-60 cm; peso de 80-150 g.', 'Depredador de insectos y pequeños roedores.', 'Preocupación Menor (LC)', 'El halcón más pequeño de América, con plumaje rojizo y patrones faciales distintivos. Se posa en lugares altos para buscar presas.', 'Desde Canadá hasta Tierra del Fuego.', 'Falconidae'),
(uuid_generate_v4(), 'Andigena nigrirostris', 'Tucán andino de pico negro (Terlaque Andino)', 'Ave', 'Bosques de niebla y subpáramos, ocasionalmente bordes de páramo.', 'Longitud de 45-50 cm; peso de 300-400 g.', 'Frugívoro, dispersor de semillas.', 'Casi Amenazada (NT)', 'Tucán de tamaño mediano con un pico negro y un plumaje colorido. Habita en los bosques húmedos andinos, pero puede ser visto en zonas de transición hacia el páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Ramphastidae'),
(uuid_generate_v4(), 'Penelope montagnii', 'Pava andina', 'Ave', 'Bosques andinos, subpáramos y zonas arbustivas de páramo.', 'Longitud de 50-60 cm; peso de 1-1.5 kg.', 'Frugívoro, dispersor de semillas, herbívoro.', 'Casi Amenazada (NT)', 'Ave galliforme de plumaje pardo, con cresta y carúnculas rojas en la cara. Se alimenta de frutos, hojas e insectos en el sotobosque y la vegetación densa.', 'Andes de Colombia, Ecuador, Perú y Venezuela.', 'Cracidae'),
(uuid_generate_v4(), 'Anas andium', 'Pato andino, cerceta andina', 'Ave', 'Lagunas, ríos y humedales de páramo y alta montaña.', 'Longitud de 38-45 cm; peso de 400-600 g.', 'Omnívoro (plantas acuáticas, insectos, pequeños invertebrados), controlador de poblaciones de insectos acuáticos.', 'Preocupación Menor (LC)', 'Pato de tamaño mediano con plumaje predominantemente pardo, que se encuentra en cuerpos de agua dulce de los Andes. Se alimenta buceando.', 'Andes de Colombia, Ecuador y Perú.', 'Anatidae'),
(uuid_generate_v4(), 'Oxypogon guerinii', 'Colibrí chivito de páramo bogotano (Bearded Helmetcrest)', 'Ave', 'Páramos y superpáramos con frailejones y vegetación arbustiva.', 'Longitud de 11-13 cm; peso de 5-7 g.', 'Polinizador de frailejones y otras plantas de páramo.', 'En Peligro (EN) - Considerada una subespecie, algunas autoridades lo elevan a especie.', 'Colibrí endémico de los páramos de la Cordillera Oriental de Colombia, con una distintiva "barba" iridiscente y un penacho en la cabeza.', 'Páramos de Colombia (Cundinamarca y Boyacá).', 'Trochilidae'),
(uuid_generate_v4(), 'Oreotrochilus estella', 'Colibrí estrella ecuatoriano', 'Ave', 'Páramos y superpáramos de alta montaña.', 'Longitud de 13-14 cm; peso de 8-10 g.', 'Polinizador de plantas de páramo.', 'Preocupación Menor (LC)', 'Gran colibrí adaptado a las altitudes extremas, con un plumaje iridiscente en el cuello. Se alimenta de néctar de flores resistentes al frío.', 'Andes de Ecuador, Perú y Bolivia (posiblemente sur de Colombia).', 'Trochilidae'),
(uuid_generate_v4(), 'Aglaeactis cupripennis', 'Colibrí rayito de sol brillante', 'Ave', 'Páramos, bosques de niebla y zonas de transición.', 'Longitud de 12-14 cm; peso de 6-8 g.', 'Polinizador.', 'Preocupación Menor (LC)', 'Colibrí con plumaje brillante y tornasolado, especialmente en las alas. Habita en áreas montañosas, visitando flores de Ericaceae y otras plantas de páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Trochilidae'),
(uuid_generate_v4(), 'Lesbia victoriae', 'Colibrí coludo azul', 'Ave', 'Páramos y subpáramos.', 'Longitud de 18-20 cm (incluyendo cola); peso de 4-6 g.', 'Polinizador.', 'Preocupación Menor (LC)', 'Colibrí de cola extremadamente larga y bifurcada, de color azul metálico. Es un visitante frecuente de las flores de páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Trochilidae'),
(uuid_generate_v4(), 'Eriocnemis vestita', 'Calzadito reluciente', 'Ave', 'Páramos y bosques de niebla.', 'Longitud de 9-11 cm; peso de 4-5 g.', 'Polinizador.', 'Preocupación Menor (LC)', 'Colibrí con llamativas "botas" de plumas blancas en las patas, y plumaje verde iridiscente. Se alimenta del néctar de diversas flores de páramo.', 'Andes de Colombia y Venezuela.', 'Trochilidae'),
(uuid_generate_v4(), 'Pterophanes cyanopterus', 'Colibrí gigante de alas azules', 'Ave', 'Páramos y superpáramos (zonas con frailejones).', 'Longitud de 18-20 cm; peso de 12-15 g.', 'Polinizador de frailejones y otras flores grandes de páramo.', 'Preocupación Menor (LC)', 'Uno de los colibríes más grandes, con alas de un brillante color azul. Se especializa en alimentarse del néctar de las flores de frailejones, siendo un polinizador clave.', 'Andes de Colombia, Ecuador y Perú.', 'Trochilidae'),
(uuid_generate_v4(), 'Coeligena helianthea', 'Inca ventriazul', 'Ave', 'Páramos y bosques de niebla.', 'Longitud de 12-14 cm; peso de 6-8 g.', 'Polinizador.', 'Preocupación Menor (LC)', 'Colibrí de plumaje oscuro con parches iridiscentes en el vientre y la garganta. Se alimenta del néctar de flores tubulares en el páramo y el bosque altoandino.', 'Andes de Colombia y Venezuela.', 'Trochilidae'),
(uuid_generate_v4(), 'Metallura tyrianthina', 'Metalura tiria', 'Ave', 'Páramos, subpáramos y bosques de niebla.', 'Longitud de 10-12 cm; peso de 4-6 g.', 'Polinizador.', 'Preocupación Menor (LC)', 'Pequeño colibrí de cola corta y plumaje verde iridiscente, con una mancha brillante en la garganta. Común en los páramos, visitando una variedad de flores.', 'Andes de Colombia, Ecuador, Perú y Venezuela.', 'Trochilidae'),
(uuid_generate_v4(), 'Grallaria quitensis', 'Tororoi leonado (Tawny Antpitta)', 'Ave', 'Páramos y subpáramos con vegetación densa.', 'Longitud de 14-16 cm; peso de 50-70 g.', 'Insectívoro terrestre, depredador de invertebrados del suelo.', 'Preocupación Menor (LC)', 'Ave terrestre de plumaje pardo, difícil de ver pero fácil de escuchar por su canto característico. Se alimenta de insectos y gusanos en el suelo del páramo.', 'Andes de Colombia, Ecuador y Perú.', 'Grallariidae'),
(uuid_generate_v4(), 'Scytalopus spillmanni', 'Tapaculo de Spillmann', 'Ave', 'Páramos y subpáramos con vegetación densa.', 'Longitud de 10-11 cm; peso de 20-25 g.', 'Insectívoro terrestre, depredador de pequeños invertebrados.', 'Preocupación Menor (LC)', 'Ave pequeña y de hábitos muy reservados, con plumaje oscuro y canto peculiar. Vive en la densa vegetación del páramo y se alimenta en el suelo.', 'Andes de Colombia y Ecuador.', 'Rhinocryptidae'),
(uuid_generate_v4(), 'Cinclodes fuscus', 'Cinclodes alifranjeado (Bar-winged Cinclodes)', 'Ave', 'Páramos, superpáramos, zonas rocosas y cerca de cuerpos de agua.', 'Longitud de 14-16 cm; peso de 30-40 g.', 'Insectívoro (invertebrados acuáticos y terrestres), carroñero.', 'Preocupación Menor (LC)', 'Ave terrestre con plumaje pardo y una distintiva franja alar. Se alimenta en el suelo, a menudo cerca de agua, y es conocido por su comportamiento inquisitivo.', 'Andes de Sudamérica.', 'Furnariidae'),
(uuid_generate_v4(), 'Muscisaxicola alpinus', 'Dormilona alpina', 'Ave', 'Páramos y superpáramos (zonas abiertas y rocosas).', 'Longitud de 17-19 cm; peso de 30-40 g.', 'Insectívoro (atrapa insectos al vuelo o en el suelo).', 'Preocupación Menor (LC)', 'Ave de plumaje grisáceo, con la cabeza más oscura y una banda blanca en las alas. Se posa en rocas o arbustos bajos desde donde observa y caza insectos.', 'Andes de Colombia, Ecuador, Perú y Bolivia.', 'Tyrannidae'),
(uuid_generate_v4(), 'Cistothorus apolinari', 'Cucarachero de pantano de Apolinar', 'Ave', 'Humedales y pantanos de páramo con vegetación densa.', 'Longitud de 12-14 cm; peso de 10-15 g.', 'Insectívoro.', 'En Peligro (EN) - Endémico de Colombia.', 'Pequeña ave endémica de los humedales altoandinos de Colombia, con plumaje pardo y canto melódico. Vive oculto entre la vegetación densa de los pantanos.', 'Cundinamarca y Boyacá (Colombia).', 'Troglodytidae'),
(uuid_generate_v4(), 'Zonotrichia capensis', 'Copetón, gorrión de collar rufo', 'Ave', 'Amplia variedad de hábitats, incluyendo páramos, zonas rurales y urbanas.', 'Longitud de 14-16 cm; peso de 20-30 g.', 'Granívoro, insectívoro, omnívoro oportunista.', 'Preocupación Menor (LC)', 'Ave pequeña y muy común en América Latina, conocida por su cabeza con rayas negras y blancas y un "collar" rojizo. Se alimenta de semillas e insectos en el suelo.', 'Desde México hasta Tierra del Fuego.', 'Passerellidae'),
(uuid_generate_v4(), 'Phrygilus unicolor', 'Fringilo plomizo', 'Ave', 'Páramos y superpáramos (zonas abiertas y rocosas).', 'Longitud de 15-17 cm; peso de 25-35 g.', 'Granívoro (semillas de gramíneas y arbustos de páramo).', 'Preocupación Menor (LC)', 'Ave de plumaje gris uniforme, adaptada a las alturas. Se alimenta en el suelo, buscando semillas entre la vegetación del páramo.', 'Andes de Colombia, Ecuador, Perú, Bolivia, Chile y Argentina.', 'Thraupidae'),
(uuid_generate_v4(), 'Diglossa humeralis', 'Pinchaflor negro', 'Ave', 'Bosques andinos, subpáramos y bordes de páramo.', 'Longitud de 13-14 cm; peso de 15-20 g.', 'Nectarívoro (perfora la base de las flores para obtener néctar), insectívoro.', 'Preocupación Menor (LC)', 'Ave de plumaje negro uniforme, con un parche azul brillante en el hombro. Se alimenta del néctar de las flores y pequeños insectos.', 'Andes de Colombia y Ecuador.', 'Thraupidae'),
(uuid_generate_v4(), 'Anisognathus igniventris', 'Tangara montana ventriescarlata', 'Ave', 'Bosques de niebla y subpáramos.', 'Longitud de 18-20 cm; peso de 40-50 g.', 'Frugívoro, insectívoro.', 'Preocupación Menor (LC)', 'Tangara grande y colorida, con un llamativo vientre escarlata. Habita en los bosques montanos, pero puede ser vista en zonas de transición hacia el páramo, alimentándose de frutos e insectos.', 'Andes de Colombia, Ecuador y Perú.', 'Thraupidae'),
(uuid_generate_v4(), 'Atlapetes schistaceus', 'Gorrión montés pizarroso', 'Ave', 'Bosques de niebla, subpáramos y bordes de páramo.', 'Longitud de 16-18 cm; peso de 25-35 g.', 'Insectívoro, granívoro, frugívoro.', 'Preocupación Menor (LC)', 'Ave con plumaje gris pizarra, cara más oscura y una corona rojiza. Se alimenta en el sotobosque y la vegetación densa de los bosques andinos y páramos.', 'Andes de Colombia, Ecuador y Perú.', 'Passerellidae'),

-- ANFIBIOS
(uuid_generate_v4(), 'Pristimantis bogotensis', 'Coquí de Bogotá (rana de lluvia)', 'Anfibio', 'Páramos, subpáramos y bosques altoandinos de la Cordillera Oriental de Colombia.', 'Longitud de 1.5 - 3 cm.', 'Control de insectos, presa para aves y mamíferos pequeños, bioindicador de la calidad del ecosistema.', 'En Peligro (EN)', 'Rana pequeña de hábitos terrestres y nocturnos, endémica de los Andes colombianos. Su reproducción es directa, sin fase de renacuajo acuático libre.', 'Cordillera Oriental de Colombia.', 'Craugastoridae'),
(uuid_generate_v4(), 'Atelopus muisca', 'Rana arlequín de Muisca', 'Anfibio', 'Páramos y zonas de alta montaña (asociada a arroyos).', 'Longitud de 3-5 cm.', 'Control de insectos, presa para depredadores, bioindicador.', 'En Peligro Crítico (CR), posiblemente Extinta (PE)', 'Especie críticamente amenazada, posiblemente extinta, de rana arlequín. Era característica de los arroyos y quebradas de páramo, muy sensible a la quitridiomicosis y pérdida de hábitat.', 'Páramos de Colombia (Cundinamarca y Boyacá).', 'Bufonidae'),
(uuid_generate_v4(), 'Dendropsophus labialis', 'Ranita verde de quebrada', 'Anfibio', 'Bosques húmedos y subpáramos, cerca de cuerpos de agua.', 'Longitud de 2-3.5 cm.', 'Control de insectos, presa para aves y pequeños depredadores.', 'Preocupación Menor (LC)', 'Pequeña rana arbórea de color verde brillante, que habita en la vegetación cercana a cuerpos de agua. Se reproduce en charcos y arroyos.', 'Andes de Colombia.', 'Hylidae'),

-- REPTILES
(uuid_generate_v4(), 'Stenocercus trachycephalus', 'Lagartija de collar espinosa', 'Reptil', 'Páramos, subpáramos y zonas rocosas.', 'Longitud de cuerpo 10-15 cm; longitud total hasta 30 cm.', 'Depredador de insectos, presa para aves rapaces.', 'Preocupación Menor (LC)', 'Lagartija terrestre de tamaño mediano con escamas ásperas y una cresta espinosa. Se camufla bien en el suelo rocoso del páramo.', 'Andes de Colombia y Ecuador.', 'Tropiduridae'),
(uuid_generate_v4(), 'Riama striata', 'Lagartija listada de páramo', 'Reptil', 'Páramos y subpáramos (zonas húmedas y con vegetación densa).', 'Longitud de cuerpo 5-8 cm; longitud total hasta 15 cm.', 'Depredador de pequeños invertebrados, presa para aves y mamíferos.', 'Preocupación Menor (LC)', 'Pequeña lagartija de cuerpo alargado y brillante, con rayas longitudinales, que se desliza entre la vegetación densa y la hojarasca del páramo húmedo.', 'Andes de Colombia y Ecuador.', 'Gymnophthalmidae'),

-- INSECTOS
(uuid_generate_v4(), 'Bombus rubicundus', 'Abejorro de páramo', 'Insecto', 'Páramos y subpáramos.', 'Longitud de 1.5-2.5 cm.', 'Polinizador clave de muchas plantas de páramo, incluyendo frailejones.', 'Datos Insuficientes (DD) - Muchas especies de Bombus están amenazadas.', 'Abejorro robusto y peludo, adaptado a las bajas temperaturas de la altura. Es un polinizador eficiente de numerosas flores de páramo, incluyendo las de frailejón.', 'Andes de Colombia y Ecuador.', 'Apidae'),
(uuid_generate_v4(), 'Colias dimera', 'Mariposa amarilla de los Andes', 'Insecto', 'Páramos y zonas abiertas de alta montaña.', 'Envergadura alar de 4-5 cm.', 'Polinizador, fuente de alimento para aves e insectívoros.', 'Preocupación Menor (LC)', 'Mariposa de color amarillo brillante, común en los páramos andinos, donde vuela entre las flores para alimentarse de néctar.', 'Andes de Colombia, Ecuador y Perú.', 'Pieridae'),
(uuid_generate_v4(), 'Vanessa virginiensis', 'Mariposa Vanesa americana', 'Insecto', 'Amplia distribución, llega a páramos (migratoria).', 'Envergadura alar de 5-6 cm.', 'Polinizador, fuente de alimento.', 'Preocupación Menor (LC)', 'Mariposa de tamaño mediano con patrones naranjas y marrones, conocida por sus migraciones. Puede encontrarse en los páramos durante ciertas épocas.', 'América del Norte y partes de Sudamérica.', 'Nymphalidae'),
(uuid_generate_v4(), 'Andiperla willinki', 'Plecóptero de glaciares', 'Insecto', 'Arroyos y ríos muy fríos de páramos y glaciares.', 'Longitud de 1-3 cm.', 'Descomponedor de materia orgánica, bioindicador de aguas prístinas.', 'Datos Insuficientes (DD)', 'Insecto acuático (ninfas) que habita en las aguas extremadamente frías de deshielo de glaciares y páramos, indicando la pureza del agua.', 'Andes del sur (Chile/Argentina), pero existen especies similares en Andes tropicales.', 'Gripopterygidae'),
(uuid_generate_v4(), 'Tipula (género)', 'Zancudos gigantes de páramo', 'Insecto', 'Páramos (zonas húmedas y vegetación baja).', 'Longitud de cuerpo 2-5 cm.', 'Las larvas son descomponedores de materia orgánica en el suelo. Los adultos son alimento para aves y murciélagos.', 'No evaluado (NE) - Género muy diverso.', 'Grupo de dípteros grandes, con patas largas, que se asemejan a mosquitos gigantes. Las larvas son importantes para el ciclo de nutrientes en los suelos del páramo.', 'Distribución global.', 'Tipulidae'),

-- PECES
(uuid_generate_v4(), 'Astroblepus grixalvii', 'Capitán de la sabana, pez gato de los Andes', 'Pez', 'Ríos y quebradas de montaña, incluyendo zonas altas de páramo.', 'Longitud de 10-20 cm.', 'Depredador de invertebrados acuáticos, bioindicador de calidad del agua.', 'Vulnerable (VU)', 'Pez bagre nativo de aguas frías y oxigenadas de los Andes, con ventosas para adherirse a las rocas. Su presencia es un indicador de ecosistemas acuáticos sanos.', 'Cuencas andinas de Colombia.', 'Astroblepidae'),
(uuid_generate_v4(), 'Trichomycterus bogotensis', 'Guapucha', 'Pez', 'Sistemas acuáticos de páramo, subpáramo y sabana de Bogotá.', 'Longitud de 5-15 cm.', 'Depredador de pequeños invertebrados, presa para aves acuáticas.', 'En Peligro Crítico (CR)', 'Pez nativo de cuerpo alargado y sin escamas, endémico de los sistemas acuáticos altoandinos, especialmente en la Sabana de Bogotá y zonas de páramo. Su población ha disminuido drásticamente.', 'Cuencas andinas de Colombia (principalmente Sabana de Bogotá).', 'Trichomycteridae');

-- Opcional: Confirmar la transacción
COMMIT;